//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Controls;

    public partial class Contracts
    {
        public int Id { get; set; }
        public string Create { get { return CreationDate.ToString("dd/MM/yyyy"); } }
        public string Update { get { return LastUpdate.ToString("dd/MM/yyyy"); } }
        public bool Check { get; set; }
        public System.DateTime CreationDate { get; set ; }
        public System.DateTime LastUpdate { get; set; }
    }
}
